# -*- coding: utf-8 -*-
"""Imagem estática

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AQthA3GztBzox3BGwwFzs0YFvitLLRBl
"""

import cv2
import numpy as np

# Carrega a imagem
img = cv2.imread('teste.jpg')

from RASP.rasp import GPIOmanager
from image_detector import ImageDetector

width = 160
height = 196 

GPIO = GPIOmanager(width,height)
DETECTOR = ImageDetector(width,height)

center_x_mm, center_y_mm, frame = DETECTOR.retrieveCoordinates(img)
print(center_x_mm,center_y_mm)
cv2.imshow('Camera', frame)
GPIO.update_dc(center_x_mm,center_y_mm)
cv2.waitKey(0)
